export interface Question {
  id: number;
  q: string;
  options: string[];
  answer: number;
}

export interface ExamCategory {
  id: string;
  title: string;
  description: string;
  durationMin: number;
  accent: string;
  icon: string;
  marksPerQuestion: number;
  negativeMarkFraction: number;
  questions: Question[];
  /**
   * Optional named sections describing inclusive question-number ranges.
   * When set, questions are NOT shuffled (only the options are), so the
   * candidate sees the same Q1–Q? sequence as defined here.
   */
  sections?: { name: string; from: number; to: number }[];
  /**
   * Scheduled date/time window for the official exam round, shown on the
   * dashboard tile and the instructions screen.
   */
  schedule?: {
    round: number;        // e.g. 1 for "Round 1"
    date: string;         // human-readable, e.g. "18 Jun 2026"
    time: string;         // human-readable, e.g. "09:00 AM – 11:00 AM"
    durationLabel: string;// e.g. "2 Hours"
    /** ISO 8601 with explicit timezone offset (IST +05:30). */
    startAt: string;
    /** ISO 8601 with explicit timezone offset (IST +05:30). */
    endAt: string;
  };
}

const placeholder = (topic: string): Question[] =>
  Array.from({ length: 5 }).map((_, i) => ({
    id: i + 1,
    q: `[${topic}] Sample question ${i + 1} - replace with real question.`,
    options: ["Option A", "Option B", "Option C", "Option D"],
    answer: 0,
  }));

const Q = (id: number, q: string, options: string[], answer: number): Question => ({ id, q, options, answer });

const aptitudeQuestions: Question[] = [
  // ────────────────────────────────────────────────────────────────
  // Section A — Numerical Ability (Q1–Q20)
  // ────────────────────────────────────────────────────────────────
  Q(1, "A contractor agreed to complete a road-laying project in 48 days using 36 workers. After working for 12 days, it was found that only one-fifth of the work had been completed because the soil conditions were harder than expected. How many additional workers must be employed so that the remaining work is completed in the next 24 days?",
    ["18", "24", "30", "36"], 3),
  Q(2, "A merchant marked an electronic item 50% above cost price and offered two successive discounts of 15% and 10%. If the final selling price was ₹11,475 and transportation charges of ₹375 were borne by the merchant, what was the original cost price of the item?",
    ["₹8,500", "₹8,750", "₹9,000", "₹9,250"], 2),
  Q(3, "Two trains start simultaneously from opposite ends of a 540 km track and travel towards each other. The first train moves 20% faster than the second and they meet after 4 hours and 30 minutes. What is the speed of the faster train?",
    ["64 km/hr", "72 km/hr", "80 km/hr", "96 km/hr"], 1),
  Q(4, "A tank can be filled by pipe A in 18 hours and by pipe B in 24 hours, while a leak can empty the full tank in 36 hours. If all three are opened together and pipe B is closed after 4 hours, how much additional time will be required to fill the remaining portion of the tank?",
    ["6 hr", "6 hr 30 min", "7 hr", "7 hr 30 min"], 2),
  Q(5, "A sum invested at compound interest amounts to ₹72,900 in 2 years and ₹88,209 in 3 years. Assuming annual compounding and no withdrawals, what was the original principal?",
    ["₹54,000", "₹60,000", "₹62,500", "₹67,500"], 0),
  Q(6, "The present ages of a father and daughter are in the ratio 7:2. Eight years ago the father's age was five times the daughter's age. After how many years from now will the father's age become exactly three times the daughter's age?",
    ["8", "10", "12", "14"], 0),
  Q(7, "A boat travels 48 km downstream in 3 hours and returns the same distance upstream in 6 hours. If the river current remains constant throughout the journey, what is the speed of the boat in still water?",
    ["10 km/hr", "12 km/hr", "14 km/hr", "16 km/hr"], 1),
  Q(8, "A bag contains 6 red, 5 blue, and 4 green balls. Three balls are drawn at random without replacement. What is the probability that all three balls are of different colors?",
    ["24/91", "30/91", "36/91", "40/91"], 0),
  Q(9, "The average marks of 30 students were calculated as 68. Later it was discovered that one student's marks were entered as 46 instead of 64 and another student's marks were entered as 83 instead of 38. What is the correct average?",
    ["66.5", "67.5", "68.1", "69.1"], 1),
  Q(10, "A trader sells two articles for ₹2,400 each. On one article he gains 25%, while on the other he loses 20%. Considering both transactions together, what is his overall percentage gain or loss?",
    ["1% gain", "2% gain", "2% loss", "4% loss"], 2),
  Q(11, "A number is increased by 20% and the result is then decreased by 25%. If the final value obtained is 1,440, what was the original number?",
    ["1,440", "1,500", "1,560", "1,600"], 3),
  Q(12, "A company's population of employees increased by 15% in the first year and decreased by 10% in the second year. If the final number of employees is 2,070, what was the original number of employees?",
    ["1,900", "2,000", "2,100", "2,200"], 1),
  Q(13, "A work can be completed by A and B together in 12 days, while B and C together can complete it in 15 days. A alone takes 20 days to complete the work. How many days will C alone take?",
    ["24", "30", "40", "60"], 1),
  Q(14, "A shopkeeper mixes rice costing ₹42 per kg with rice costing ₹58 per kg and sells the mixture at ₹55 per kg, thereby making a profit of 10% on the mixture. In what ratio were the two varieties mixed?",
    ["1:2", "2:3", "3:5", "4:5"], 0),
  Q(15, "The difference between compound interest and simple interest on a certain sum for 2 years at 10% per annum is ₹480. What is the principal amount?",
    ["₹40,000", "₹48,000", "₹60,000", "₹72,000"], 1),
  Q(16, "A train travelling at 72 km/hr crosses a platform in 45 seconds and a man walking at 6 km/hr in the same direction in 18 seconds. What is the length of the platform?",
    ["420 m", "450 m", "480 m", "540 m"], 3),
  Q(17, "A sum doubles itself in 8 years at simple interest. In how many years will the same sum become three times itself under the same rate of interest?",
    ["12", "14", "16", "18"], 2),
  Q(18, "A dishonest milkman adds water to milk and gains 25% while selling the mixture at the cost price of pure milk. What percentage of the mixture is water?",
    ["16 2/3%", "20%", "25%", "33 1/3%"], 1),
  Q(19, "How many five-digit numbers can be formed using the digits 1, 2, 3, 4, and 5 without repetition such that the number is divisible by 5 and greater than 30,000?",
    ["12", "18", "24", "36"], 0),
  Q(20, "A number leaves remainder 5 when divided by 8, 12, and 18. What is the smallest such number greater than 500?",
    ["509", "581", "653", "725"], 0),

  // ────────────────────────────────────────────────────────────────
  // Section B — Verbal Ability (Q21–Q45)
  // ────────────────────────────────────────────────────────────────
  Q(21, "Choose the grammatically correct sentence.",
    ["Neither the director nor the employees was aware of the revised schedule.",
     "Neither the director nor the employees were aware of the revised schedule.",
     "Neither the director nor the employees has aware of the revised schedule.",
     "Neither the director nor the employees have aware of the revised schedule."], 1),
  Q(22, "Identify the sentence with the correct use of articles.",
    ["She is a honest officer with an excellent record.",
     "She is an honest officer with a excellent record.",
     "She is an honest officer with an excellent record.",
     "She is a honest officer with a excellent record."], 2),
  Q(23, "Choose the word closest in meaning to \"meticulous\".",
    ["Careless", "Thorough", "Temporary", "Impulsive"], 1),
  Q(24, "Choose the word opposite in meaning to \"transient\".",
    ["Fleeting", "Permanent", "Fragile", "Partial"], 1),
  Q(25, "Fill in the blank: Despite repeated assurances from management regarding job security, employees remained ______ about the future because the company's profits had declined for three consecutive quarters.",
    ["jubilant", "apprehensive", "indifferent", "complacent"], 1),
  Q(26, "Fill in the blank: The professor's explanation was so ______ that even students with no prior exposure to the subject could follow the argument without difficulty.",
    ["obscure", "lucid", "ambiguous", "verbose"], 1),
  Q(27, "Identify the error in: \"Each of the candidates have submitted their project reports before the deadline.\"",
    ["Each", "have", "their", "No error"], 1),
  Q(28, "Choose the correctly punctuated sentence.",
    ["After reviewing the report, the manager approved the proposal.",
     "After reviewing the report the manager, approved the proposal.",
     "After reviewing, the report the manager approved the proposal.",
     "After reviewing the report the manager approved, the proposal."], 0),
  Q(29, "Rearrange the following statements into a coherent paragraph: 1. The prototype exceeded expectations during testing. 2. Investors immediately showed interest in funding the project. 3. The startup had struggled for months to attract attention. 4. Positive media coverage followed shortly afterward.",
    ["3-1-2-4", "1-3-2-4", "2-4-3-1", "4-2-1-3"], 0),
  Q(30, "Choose the best replacement for the underlined part: \"The committee COMPRISED OF experts from different fields met yesterday.\"",
    ["comprised with", "was comprised of", "comprised", "comprising of"], 2),
  Q(31, "Select the sentence that is free from grammatical errors.",
    ["Hardly had the meeting begun when the power failed.",
     "Hardly the meeting had begun when the power failed.",
     "Hardly had begun the meeting when the power failed.",
     "Hardly the meeting begun when the power had failed."], 0),
  Q(32, "Choose the most appropriate word: The CEO's decision was not merely unpopular; it was widely regarded as ______ because it ignored all the evidence presented by the advisory panel.",
    ["prudent", "arbitrary", "generous", "cautious"], 1),
  Q(33, "Identify the sentence with the correct subject-verb agreement.",
    ["The quality of the products have improved significantly.",
     "The quality of the products has improved significantly.",
     "The quality of the products are improved significantly.",
     "The quality of the products were improved significantly."], 1),
  Q(34, "Choose the correct passive form: \"They will announce the results tomorrow.\"",
    ["The results will be announce tomorrow.",
     "The results will announced tomorrow.",
     "The results will be announced tomorrow.",
     "The results are announced tomorrow."], 2),
  Q(35, "Choose the correct indirect speech: Ravi said, \"I have completed the assignment.\"",
    ["Ravi said that he has completed the assignment.",
     "Ravi said that he had completed the assignment.",
     "Ravi said that I had completed the assignment.",
     "Ravi said that he completed the assignment."], 1),
  Q(36, "Choose the best word to complete the sentence: The researcher remained ______ in her conclusions, avoiding claims that the available data could not adequately support.",
    ["reckless", "tentative", "hostile", "indifferent"], 1),
  Q(37, "Select the correctly formed sentence.",
    ["No sooner did he arrive than the train departed.",
     "No sooner had he arrived when the train departed.",
     "No sooner did he arrive when the train departed.",
     "No sooner had he arrived than the train departed."], 3),
  Q(38, "Choose the most suitable meaning of the idiom \"spill the beans\".",
    ["Waste resources", "Reveal a secret", "Start an argument", "Make a mistake"], 1),
  Q(39, "Choose the one-word substitution for \"a person who studies ancient societies through material remains\".",
    ["Anthropologist", "Archaeologist", "Geologist", "Historian"], 1),
  Q(40, "Fill in the blank: The policy was introduced with the intention of reducing costs; ______, it ended up increasing administrative overhead.",
    ["therefore", "moreover", "however", "similarly"], 2),
  Q(41, "Identify the error in: \"Neither of the proposals were acceptable to the board because both lacked financial justification.\"",
    ["Neither", "were", "both", "No error"], 1),
  Q(42, "Choose the sentence that conveys the intended meaning most clearly.",
    ["After discussing the issue with the client, the report was revised.",
     "After discussing the issue with the client, the team revised the report.",
     "After discussing, the client revised the issue in the report.",
     "After the issue was discussed, the client and report were revised."], 1),
  Q(43, "Choose the most appropriate transition: The initial experiments produced inconsistent results. ______, the researchers redesigned the methodology before proceeding to the next phase.",
    ["Consequently", "Nevertheless", "Likewise", "Meanwhile"], 0),
  Q(44, "Choose the correct form: If the company ______ the warning signs earlier, it could have avoided the financial crisis.",
    ["notices", "noticed", "had noticed", "has noticed"], 2),
  Q(45, "Choose the sentence with the correct parallel structure.",
    ["The role requires planning campaigns, analyzing data, and communication with clients.",
     "The role requires planning campaigns, data analysis, and communicating with clients.",
     "The role requires to plan campaigns, analyzing data, and client communication.",
     "The role requires campaign planning, analyze data, and communicating with clients."], 1),

  // ────────────────────────────────────────────────────────────────
  // Section C — Reasoning Ability (Q46–Q65)
  // ────────────────────────────────────────────────────────────────
  Q(46, "In a certain code language, \"MOUNTAIN\" is written as \"NTVOUJBN\". Following the same pattern, how will \"JOURNEY\" be written?",
    ["KPVSOFZ", "KQVSNFZ", "LPVSOFY", "KPVTNGZ"], 0),
  Q(47, "Six friends P, Q, R, S, T, and U are seated around a circular table facing the center. P sits second to the left of Q, R sits opposite U, and T is an immediate neighbor of both P and U. Who sits opposite Q?",
    ["P", "R", "S", "T"], 3),
  Q(48, "A man walks 15 m north, turns right and walks 25 m, turns right again and walks 10 m, and then turns left and walks 20 m. How far and in which direction is he from the starting point?",
    ["30 m East", "35 m East", "25 m North-East", "30 m South-East"], 0),
  Q(49, "Statements: All laptops are devices. Some devices are tablets. No tablet is a desktop. Conclusions: I. Some laptops are tablets. II. No laptop is a desktop.",
    ["Only I follows", "Only II follows", "Both follow", "Neither follows"], 3),
  Q(50, "Find the next term in the series: 4, 9, 19, 39, 79, ?",
    ["119", "139", "159", "169"], 2),
  Q(51, "Pointing to a woman, Raj said, \"She is the daughter of the only son of my grandfather.\" How is the woman related to Raj?",
    ["Sister", "Daughter", "Niece", "Cousin"], 0),
  Q(52, "Arrange the following in a logical sequence: 1. Treatment 2. Recovery 3. Patient 4. Doctor 5. Hospital",
    ["4-5-3-1-2", "3-4-5-1-2", "5-4-3-2-1", "4-3-5-1-2"], 1),
  Q(53, "If South-East becomes North, North-East becomes West, and West becomes South-East, then East becomes which direction?",
    ["South", "North-East", "North-West", "South-West"], 2),
  Q(54, "Statements: All engineers are graduates. Some graduates are managers. Conclusions: I. Some engineers are managers. II. Some managers are graduates.",
    ["Only I follows", "Only II follows", "Both follow", "Neither follows"], 1),
  Q(55, "Find the missing term: AZ, BY, CX, DW, ?",
    ["EV", "FU", "EW", "FV"], 0),
  Q(56, "A cube is painted on all six faces and then cut into 125 smaller cubes of equal size. How many small cubes will have exactly two faces painted?",
    ["12", "24", "36", "48"], 2),
  Q(57, "Five students are ranked from 1 to 5. A is ranked above B but below C. D is below B, and E is above A but below C. Who is ranked third?",
    ["A", "B", "D", "E"], 0),
  Q(58, "Find the odd one out: 64, 125, 216, 343, 512, 625.",
    ["125", "216", "512", "625"], 3),
  Q(59, "If \"TABLE\" is coded as \"UBCMF\", then \"CHAIR\" will be coded as:",
    ["DIBJS", "DIBKT", "DICJS", "EIBJS"], 0),
  Q(60, "A clock shows 4:20. What is the angle between the hour hand and the minute hand?",
    ["10°", "20°", "30°", "40°"], 0),
  Q(61, "In a row of children, Ravi is 12th from the left and 18th from the right. How many children are there in the row?",
    ["28", "29", "30", "31"], 1),
  Q(62, "Find the next term: 3, 8, 18, 38, 78, ?",
    ["118", "138", "158", "178"], 2),
  Q(63, "Statements: Some books are magazines. All magazines are journals. Conclusions: I. Some books are journals. II. All books are journals.",
    ["Only I follows", "Only II follows", "Both follow", "Neither follows"], 0),
  Q(64, "A family consists of six members P, Q, R, S, T, and U. P is the father of Q, Q is the sister of R, S is the mother of T, and T is the son of P. If U is the grandfather of R, who is the mother of R?",
    ["P", "Q", "S", "Cannot be determined"], 2),
  Q(65, "Find the missing number: 7, 14, 28, 56, ?, 224.",
    ["84", "96", "112", "128"], 2),

  // ────────────────────────────────────────────────────────────────
  // Section D — Advanced Quant & Reasoning (Q66–Q85)
  // ────────────────────────────────────────────────────────────────
  Q(66, "A company invests ₹8 lakh at 12% compound interest annually and simultaneously borrows ₹5 lakh at 15% simple interest. What is the net gain after 3 years?",
    ["₹1,15,280", "₹1,24,480", "₹1,36,960", "₹1,52,000"], 0),
  Q(67, "Two trains of lengths 180 m and 220 m cross each other in opposite directions in 12 seconds. If the difference in their speeds is 48 km/hr, what is the speed of the faster train?",
    ["60 km/hr", "72 km/hr", "84 km/hr", "96 km/hr"], 2),
  Q(68, "Find the remainder when 7^125 is divided by 13.",
    ["1", "5", "7", "11"], 3),
  Q(69, "The volume of a cube increases by 72.8%. By what percentage does its side increase?",
    ["18%", "20%", "22%", "24%"], 1),
  Q(70, "Five workers can complete a project in 24 days. After working for 8 days, two workers leave. How many additional days will be required to finish the remaining work?",
    ["18", "20", "22", "24"], 1),
  Q(71, "If x + 1/x = 5, find the value of x⁴ + 1/x⁴.",
    ["447", "527", "577", "625"], 1),
  Q(72, "A committee of 5 is selected from 6 men and 4 women such that at least 2 women must be included. How many different committees can be formed?",
    ["186", "216", "246", "276"], 0),
  Q(73, "A bag contains 8 white and 6 black balls. Two balls are drawn without replacement. What is the probability that both are white?",
    ["14/91", "24/91", "28/91", "32/91"], 2),
  Q(74, "Find the next term in the series: 2, 6, 15, 31, 56, ?",
    ["84", "90", "92", "96"], 2),
  Q(75, "A number when divided by 5 leaves remainder 2, when divided by 7 leaves remainder 3, and when divided by 9 leaves remainder 4. What is the smallest positive number satisfying all three conditions?",
    ["157", "172", "192", "227"], 0),
  Q(76, "The ratio of the radii of two circles is 3:5. If the difference in their areas is 256π square units, what is the radius of the larger circle?",
    ["12", "16", "20", "24"], 2),
  Q(77, "A train leaves station A at 6:00 AM at 60 km/hr. Another train leaves station B, 420 km away, at 7:00 AM towards A at 80 km/hr. At what time will they meet?",
    ["8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM"], 2),
  Q(78, "If log₂ 16 + log₄ 64 − log₈ 512 = ?",
    ["3", "4", "5", "6"], 1),
  Q(79, "A and B together can complete a work in 10 days, B and C together in 12 days, and A and C together in 15 days. In how many days can all three together complete the work?",
    ["6", "7", "8", "9"], 2),
  Q(80, "A dealer allows a discount of 20% on the marked price and still makes a profit of 25% on cost price. If the marked price is ₹3,000, what is the cost price?",
    ["₹1,800", "₹1,920", "₹2,000", "₹2,400"], 1),
  Q(81, "The average salary of 50 employees is ₹52,000. When the salaries of the top five employees are excluded, the average becomes ₹47,000. What is the average salary of the excluded employees?",
    ["₹92,000", "₹97,000", "₹1,02,000", "₹1,07,000"], 1),
  Q(82, "How many four-digit numbers can be formed from the digits 1, 2, 3, 4, 5, 6 without repetition such that the number is even and greater than 3,000?",
    ["120", "144", "168", "180"], 0),
  Q(83, "A mixture contains milk and water in the ratio 7:3. If 20 liters of the mixture are replaced with pure water and the resulting ratio becomes 7:5, what was the original quantity of the mixture?",
    ["80 L", "100 L", "120 L", "140 L"], 2),
  Q(84, "A cylindrical tank has radius 3 m and height 8 m. Water is filled up to 75% of its height. How many cubic meters of water does the tank contain?",
    ["48π", "54π", "60π", "72π"], 1),
  Q(85, "A number is first increased by 25%, then decreased by 20%, and finally increased by 10%. If the final value is 1,650, what was the original number?",
    ["1,200", "1,250", "1,300", "1,350"], 3),
];

const aptitudeSections = [
  { name: "Section A — Numerical Ability",          from: 1,  to: 20 },
  { name: "Section B — Verbal Ability",             from: 21, to: 45 },
  { name: "Section C — Reasoning Ability",          from: 46, to: 65 },
  { name: "Section D — Advanced Quant & Reasoning", from: 66, to: 85 },
];

const dsaQuestions: Question[] = [
  Q(1, "Which data structure uses the LIFO (Last In, First Out) principle?",
    ["Queue", "Stack", "Linked List", "Tree"], 1),
  Q(2, "What is the time complexity of Binary Search?",
    ["O(n)", "O(n²)", "O(log n)", "O(1)"], 2),
  Q(3, "Which sorting algorithm has the best worst-case time complexity?",
    ["Bubble Sort", "Quick Sort", "Merge Sort", "Selection Sort"], 2),
  Q(4, "Which data structure is best suited for implementing an \"Undo\" feature in a text editor?",
    ["Queue", "Stack", "Array", "Hash Map"], 1),
  Q(5, "What is the time complexity of inserting an element at the beginning of a Linked List?",
    ["O(n)", "O(log n)", "O(n²)", "O(1)"], 3),
  Q(6, "Which traversal of a Binary Search Tree gives elements in sorted order?",
    ["Preorder", "Postorder", "Inorder", "Level Order"], 2),
  Q(7, "What is the maximum number of nodes in a binary tree of height h?",
    ["2h", "2h - 1", "2^(h+1) - 1", "h²"], 2),
  Q(8, "In a Min-Heap, which element is always at the root?",
    ["Largest element", "Smallest element", "Middle element", "Last inserted element"], 1),
  Q(9, "Which data structure is used for BFS (Breadth First Search) in a graph?",
    ["Stack", "Tree", "Queue", "Array"], 2),
  Q(10, "What does a Hash Table use to map keys to values?",
    ["Sorting", "Indexing", "Hash Function", "Pointers"], 2),
];

// 20 Pro-Level System Design & Architecture MCQs.
const systemQuestions: Question[] = [
  Q(1, "A company stores employee details in a table where each employee has a unique Employee ID. During data insertion, two employees accidentally receive the same Employee ID. Which database concept is violated?",
    ["Foreign Key", "Primary Key", "Candidate Key", "Composite Key"], 1),
  Q(2, "A web application sends a login request to the server. The server validates credentials and returns a response. In this flow, which component acts as the intermediary between the database and the user?",
    ["Client", "Browser Cache", "Server", "Network Switch"], 2),
  Q(3, "A table contains the columns: Student_ID, Student_Name, Course_Name, Faculty_Name. If the same faculty details are repeated hundreds of times, which database issue is most likely occurring?",
    ["Data Redundancy", "Data Encryption", "Data Isolation", "Data Recovery"], 0),
  Q(4, "In a client-server application, a user clicks \"Submit.\" Before the request reaches the database, it must first pass through:",
    ["Client Application Only", "Database Directly", "Application Server", "Data Warehouse"], 2),
  Q(5, "A company wants to ensure that deleting a customer record automatically removes all associated orders. Which concept is involved?",
    ["Cascading Operation", "Data Mining", "Hashing", "Indexing"], 0),
  Q(6, "A database transaction deducts ₹500 from Account A but fails before crediting Account B. Which ACID property ensures the entire transaction is rolled back?",
    ["Consistency", "Isolation", "Durability", "Atomicity"], 3),
  Q(7, "A browser requests a webpage from a server. The server responds with HTML content. Which component is responsible for rendering the webpage?",
    ["Database", "Browser", "Application Server", "Router"], 1),
  Q(8, "A table stores Order_ID, Product_ID, Quantity. Multiple products can belong to one order. Which relationship is represented?",
    ["One-to-One", "Many-to-One", "One-to-Many", "Many-to-Many"], 2),
  Q(9, "A client sends a request to a server, but the server is temporarily unavailable. Which architecture component has failed?",
    ["Database Schema", "Server Layer", "User Interface Layer", "Data Dictionary"], 1),
  Q(10, "A company uses a column frequently in search operations. To improve retrieval speed, which database feature is most suitable?",
    ["Trigger", "Cursor", "Index", "View"], 2),
  Q(11, "A banking application allows thousands of users to access accounts simultaneously. Which database feature manages concurrent access safely?",
    ["Normalization", "Locking Mechanism", "Indexing", "Partitioning"], 1),
  Q(12, "A client application sends a request to fetch customer details. The server retrieves data from the database and sends it back. Which architecture style does this represent?",
    ["Peer-to-Peer", "Client-Server", "Monolithic Database", "Standalone Processing"], 1),
  Q(13, "A database designer separates customer information and address information into different tables to reduce duplication. This process is called:",
    ["Replication", "Denormalization", "Normalization", "Aggregation"], 2),
  Q(14, "Which statement best describes the role of a database schema?",
    ["Stores Actual Data", "Defines Database Structure", "Encrypts Records", "Executes Queries"], 1),
  Q(15, "A user updates a record while another user is reading the same record. Which ACID property minimizes inconsistent results?",
    ["Durability", "Atomicity", "Isolation", "Replication"], 2),
  Q(16, "In a three-tier architecture, which layer directly interacts with the database?",
    ["Presentation Layer", "Business Logic Layer", "Data Layer", "User Layer"], 2),
  Q(17, "A company stores customer and order information in separate tables connected through Customer_ID. Customer_ID in the Orders table is an example of:",
    ["Primary Key", "Candidate Key", "Foreign Key", "Alternate Key"], 2),
  Q(18, "Which operation generally requires the server to communicate with the database?",
    ["Rendering HTML", "Updating Customer Record", "Displaying Cached Image", "Opening Browser"], 1),
  Q(19, "A table has no repeated groups and each cell contains a single value. Which normal form is satisfied?",
    ["1NF", "2NF", "3NF", "BCNF"], 0),
  Q(20, "A user requests a webpage. Which sequence is most appropriate?",
    ["Database → Client → Server", "Client → Server → Database → Server → Client", "Server → Client → Database", "Client → Database → Browser"], 1),
  Q(21, "A database crash occurs immediately after a successful transaction commit. Which ACID property ensures committed data remains saved?",
    ["Consistency", "Isolation", "Durability", "Atomicity"], 2),
  Q(22, "A web application has Presentation Layer, Application Layer, and Database Layer. This is an example of:",
    ["Two-Tier Architecture", "Three-Tier Architecture", "Peer-to-Peer Architecture", "Flat Architecture"], 1),
  Q(23, "Which database object can provide a virtual table without storing actual data separately?",
    ["Trigger", "Index", "View", "Cursor"], 2),
  Q(24, "A server receives requests from multiple clients at the same time. Which characteristic is most important?",
    ["Concurrency Handling", "File Compression", "Data Formatting", "Data Duplication"], 0),
  Q(25, "A table contains Employee_ID, Employee_Name, Department_Name, Department_Location. Department details repeat frequently. Which anomaly is likely?",
    ["Insertion Anomaly", "Deletion Anomaly", "Update Anomaly", "All of the Above"], 3),
  Q(26, "A primary key must be:",
    ["Unique and Non-Null", "Nullable and Repeated", "Optional", "Multi-Valued"], 0),
  Q(27, "A user accesses an online shopping website through a browser. The browser is an example of:",
    ["Database Server", "Application Server", "Client", "Data Layer"], 2),
  Q(28, "What is the primary purpose of normalization?",
    ["Increase Data Redundancy", "Reduce Data Redundancy", "Increase Storage Usage", "Slow Query Performance"], 1),
  Q(29, "In a database, a transaction is:",
    ["A Backup Operation", "A Set of Related Operations Executed as One Unit", "A Network Protocol", "A Query Optimizer"], 1),
  Q(30, "A company wants multiple servers to share workload for improved performance. Which architectural concept is involved?",
    ["Load Balancing", "Indexing", "Normalization", "Tokenization"], 0),
  Q(31, "A client submits a request, but the database is never contacted because the data already exists in cache. Which component improved performance?",
    ["Cache Layer", "Trigger Layer", "Schema Layer", "Transaction Layer"], 0),
  Q(32, "Which SQL operation is generally used to retrieve data from a table?",
    ["INSERT", "UPDATE", "DELETE", "SELECT"], 3),
  Q(33, "A database contains Customers and Orders tables. One customer can place many orders. Which relationship exists?",
    ["One-to-One", "One-to-Many", "Many-to-Many", "Many-to-One"], 1),
  Q(34, "A server validates user credentials before granting access. This process primarily relates to:",
    ["Authentication", "Compression", "Replication", "Partitioning"], 0),
  Q(35, "Which architecture component is mainly responsible for storing persistent data?",
    ["Client", "Browser", "Database", "Load Balancer"], 2),
  Q(36, "A transaction updates inventory count and sales records together. If one operation fails, both should fail. Which ACID property applies?",
    ["Durability", "Atomicity", "Consistency", "Isolation"], 1),
  Q(37, "A foreign key is primarily used to:",
    ["Increase Storage", "Create Relationships Between Tables", "Encrypt Records", "Improve UI Performance"], 1),
  Q(38, "Which layer in a three-tier architecture usually contains business rules and validations?",
    ["Presentation Layer", "Data Layer", "Business Logic Layer", "Network Layer"], 2),
  Q(39, "A user submits a form, and the server processes it before writing to the database. Why is direct client-to-database communication generally avoided?",
    ["Security and Validation Concerns", "Faster Performance", "Reduced Storage", "Better UI Design"], 0),
  Q(40, "A company wants database operations to remain correct even when multiple users access data simultaneously. Which ACID property is most closely associated with this requirement?",
    ["Atomicity", "Durability", "Isolation", "Replication"], 2),
];

// 50 scenario-based debugging & integration MCQs (technical assessment).
const technicalQuestions: Question[] = [
  Q(1, "A mobile application sends a request to an API endpoint to retrieve user profile details. The request reaches the server successfully, but the client receives an empty response even though records exist in the database. The network connection is stable and the database query executes successfully.",
    ["API Authentication Failure", "Response Serialization Issue", "DNS Resolution Error", "Database Connection Timeout"], 1),
  Q(2, "A frontend application calls an API using a valid URL. The API returns HTTP Status Code 404. The backend server is running correctly and the database is accessible. Which is the most likely reason?",
    ["Endpoint Not Found", "Unauthorized Access", "Database Corruption", "API Rate Limiting"], 0),
  Q(3, "A developer integrates a payment gateway into an e-commerce application. Test payments are processed successfully, but live transactions fail immediately after deployment. The same codebase is being used in both environments.",
    ["Production Credentials Mismatch", "Incorrect HTML Structure", "Browser Cache Issue", "Invalid Database Schema"], 0),
  Q(4, "A client application sends an API request containing a JSON payload. The server responds with \"400 Bad Request.\" Network logs show that the request reached the server successfully.",
    ["Malformed Request Data", "Server Crash", "Missing Database Table", "DNS Failure"], 0),
  Q(5, "During debugging, a developer notices that a variable contains the correct value before entering a function but becomes null inside the function. No database operations are involved.",
    ["Scope Issue", "Network Congestion", "API Throttling", "Data Encryption"], 0),
  Q(6, "An application integrates with a third-party weather service API. The API key was recently regenerated, but all requests now return an authentication error.",
    ["Expired SSL Certificate", "Invalid API Key Configuration", "Database Deadlock", "Browser Rendering Error"], 1),
  Q(7, "A user submits a registration form. The frontend displays \"Success,\" but no record is inserted into the database. API logs show that the request was received.",
    ["Transaction Rollback", "DNS Cache Issue", "CSS Rendering Failure", "Browser Plugin Conflict"], 0),
  Q(8, "A debugging session reveals that an API endpoint takes 15 seconds to respond even though the database query completes in less than 1 second. Which area should be investigated first?",
    ["Business Logic Processing", "Database Indexing", "Browser Cookies", "URL Structure"], 0),
  Q(9, "A frontend developer consumes an API that returns XML data, while the application expects JSON data. Which integration issue is occurring?",
    ["Protocol Mismatch", "Data Format Mismatch", "Authentication Failure", "Load Balancing Error"], 1),
  Q(10, "An API works correctly in Postman but fails when called from a web browser application. The server logs show no incoming requests from the browser.",
    ["CORS Restriction", "Database Failure", "Data Duplication", "Memory Leak"], 0),
  Q(11, "A service integration requires data from System A to be sent automatically to System B whenever a new customer is created. Which integration style is most suitable?",
    ["Real-Time Event Integration", "Manual Export", "Static HTML Transfer", "File Compression"], 0),
  Q(12, "While debugging a login issue, a developer notices that credentials are sent correctly but authentication fails because the password hash differs from the stored value.",
    ["Encryption Mismatch", "DNS Error", "API Version Conflict", "UI Rendering Issue"], 0),
  Q(13, "A REST API returns HTTP 500 whenever a specific request parameter is provided. Other requests work normally. Which issue is most likely?",
    ["Unhandled Server Exception", "Invalid Browser Cache", "Slow Internet Connection", "Missing CSS File"], 0),
  Q(14, "An inventory application integrates with a warehouse system. Product updates appear after a delay of 24 hours even though both systems are online continuously.",
    ["Batch Integration Process", "API Authentication Failure", "Browser Security Restriction", "DNS Resolution Issue"], 0),
  Q(15, "A developer modifies an API response structure by renaming a field. Immediately afterward, the client application starts failing despite receiving responses successfully.",
    ["Contract Compatibility Issue", "Database Normalization Problem", "HTTP Compression Failure", "URL Routing Conflict"], 0),
  Q(16, "During debugging, the application behaves differently in production than in development. The code is identical in both environments.",
    ["Environment Configuration Difference", "API Protocol Failure", "Browser Rendering Bug", "SQL Syntax Error"], 0),
  Q(17, "A third-party API suddenly starts rejecting requests after months of successful operation. Investigation shows the API endpoint URL has changed.",
    ["Endpoint Deprecation", "Database Locking", "Memory Fragmentation", "Client Validation Error"], 0),
  Q(18, "A developer receives a \"401 Unauthorized\" response despite sending requests to the correct endpoint and using valid data.",
    ["Authentication Issue", "Database Timeout", "API Version Upgrade", "Network Congestion"], 0),
  Q(19, "A microservice sends requests to another service. Occasionally the target service is unavailable, causing failures. Which integration approach improves resilience?",
    ["Retry Mechanism", "Larger Database Tables", "Additional HTML Pages", "More CSS Styling"], 0),
  Q(20, "An API returns correct data but only after multiple retries. Server monitoring indicates intermittent connectivity problems.",
    ["Network Instability", "Database Normalization Error", "Invalid JSON Syntax", "API Documentation Error"], 0),
  Q(21, "A developer sets breakpoints throughout an application but execution never reaches a particular function despite expected user actions.",
    ["Function Not Being Invoked", "Database Deadlock", "SSL Certificate Expiry", "API Gateway Failure"], 0),
  Q(22, "An integration project requires transferring customer data between two systems that use different field names for the same information.",
    ["Data Mapping Requirement", "Network Segmentation", "Browser Configuration Error", "Database Partitioning"], 0),
  Q(23, "A backend service returns a successful response code, but the data received by the client is incomplete.",
    ["Partial Serialization Issue", "API Authentication Failure", "SQL Injection Attack", "DNS Timeout"], 0),
  Q(24, "While debugging an API, logs show requests arriving successfully, but responses never leave the server.",
    ["Response Processing Failure", "Database Backup Error", "Invalid HTML Markup", "Browser Session Expiry"], 0),
  Q(25, "An API integration suddenly breaks after upgrading to Version 2 of a third-party service. Existing requests remain unchanged.",
    ["Backward Compatibility Issue", "Database Trigger Failure", "DNS Caching Issue", "UI Validation Error"], 0),
  Q(26, "A system receives duplicate customer records after integration. Investigation reveals the same API request is processed multiple times.",
    ["Idempotency Problem", "Authentication Problem", "Database Recovery Issue", "Browser Synchronization Error"], 0),
  Q(27, "A developer is debugging a slow application and notices that one API call triggers five additional API calls before completion.",
    ["Excessive Chained Requests", "Database Encryption", "UI Rendering Optimization", "DNS Configuration"], 0),
  Q(28, "A frontend application consumes a secure API over HTTPS. Requests fail only when accessing from a specific corporate network.",
    ["Firewall Restriction", "Database Indexing Issue", "API Version Conflict", "Invalid JSON Response"], 0),
  Q(29, "A developer integrates two applications. One system expects dates in DD/MM/YYYY format while the other expects MM/DD/YYYY.",
    ["Data Transformation Issue", "API Authentication Failure", "DNS Lookup Error", "CSS Parsing Error"], 0),
  Q(30, "An API endpoint works perfectly for small datasets but fails when thousands of records are requested simultaneously.",
    ["Scalability Limitation", "HTML Rendering Problem", "API Key Expiration", "Browser Plugin Conflict"], 0),
  Q(31, "A debugging tool shows that an exception occurs only under heavy user load and never during normal testing.",
    ["Concurrency Issue", "Invalid Endpoint URL", "Missing CSS Resource", "Browser History Corruption"], 0),
  Q(32, "A system integration requires automatic synchronization whenever data changes in the source application.",
    ["Event-Driven Integration", "Manual Processing", "Static Deployment", "Local Storage"], 0),
  Q(33, "An API response includes all expected fields, but numerical values appear incorrect after integration.",
    ["Data Type Conversion Error", "Authentication Token Issue", "URL Routing Failure", "SSL Configuration Error"], 0),
  Q(34, "A debugging session reveals memory consumption continuously increases after every API request.",
    ["Memory Leak", "DNS Misconfiguration", "Database Normalization Issue", "Authentication Failure"], 0),
  Q(35, "A third-party API imposes a limit of 100 requests per minute. An application exceeds this threshold.",
    ["Rate Limiting Issue", "Database Constraint Violation", "Browser Cache Failure", "HTML Parsing Error"], 0),
  Q(36, "A service receives valid API requests but responds with outdated information despite recent database updates.",
    ["Caching Issue", "Network Failure", "Authentication Mismatch", "Endpoint Deprecation"], 0),
  Q(37, "A developer notices that API requests succeed locally but fail after deployment due to missing environment variables.",
    ["Configuration Management Issue", "Database Fragmentation", "CSS Conflict", "Browser Security Policy"], 0),
  Q(38, "Two integrated systems exchange data successfully, but special characters become corrupted during transfer.",
    ["Character Encoding Mismatch", "API Gateway Failure", "SQL Optimization Issue", "Network Routing Error"], 0),
  Q(39, "An API call consistently returns \"403 Forbidden\" while authentication credentials remain valid.",
    ["Authorization Restriction", "Database Deadlock", "Browser Timeout", "Data Redundancy"], 0),
  Q(40, "A developer debugs an application where the same function produces different outputs for identical inputs.",
    ["Hidden State Dependency", "DNS Failure", "API Rate Limit", "SQL Injection"], 0),
  Q(41, "A client sends a request containing 20 fields. The API accepts only 19 fields and rejects the request entirely.",
    ["Strict Schema Validation", "Browser Rendering Failure", "Database Backup Error", "CSS Parsing Issue"], 0),
  Q(42, "A large enterprise integrates HR, Payroll, and Attendance systems. Data consistency across all systems is critical.",
    ["Enterprise Application Integration", "HTML Templating", "Local File Transfer", "Browser Automation"], 0),
  Q(43, "While debugging, logs indicate that code execution stops unexpectedly without any visible error message.",
    ["Silent Exception Handling", "Database Recovery Process", "API Authentication Failure", "DNS Resolution Delay"], 0),
  Q(44, "A service receives requests successfully but occasionally processes them twice because acknowledgments are delayed.",
    ["Duplicate Processing Scenario", "Database Corruption", "Browser Compatibility Issue", "UI Synchronization Failure"], 0),
  Q(45, "An integration project requires combining customer information from three different systems into one unified format.",
    ["Data Aggregation and Mapping", "API Throttling", "Database Sharding", "Browser Session Tracking"], 0),
  Q(46, "An API request fails only when a specific optional parameter is included, even though its value appears valid.",
    ["Conditional Logic Bug", "DNS Failure", "Authentication Expiry", "Browser Cache Corruption"], 0),
  Q(47, "A debugging session shows that execution enters an infinite loop after receiving a particular API response.",
    ["Faulty Loop Condition", "Database Backup Failure", "API Endpoint Change", "SSL Misconfiguration"], 0),
  Q(48, "A company integrates a CRM system with an ERP system. Customer creation succeeds, but customer updates never appear in the ERP.",
    ["Missing Update Synchronization Logic", "DNS Timeout", "HTML Validation Failure", "Browser Cookie Issue"], 0),
  Q(49, "An API response contains nested JSON objects, but the client reads only top-level fields.",
    ["Incorrect Data Parsing Logic", "Database Normalization Error", "Firewall Restriction", "URL Redirection Failure"], 0),
  Q(50, "A developer notices that integration tests pass individually but fail when executed together in sequence. Shared resources are used across tests.",
    ["State Dependency Issue", "Authentication Token Rotation", "DNS Propagation Delay", "Browser Rendering Conflict"], 0),
];

export const EXAMS: ExamCategory[] = [
  {
    id: "aptitude",
    title: "Aptitude Test",
    description: "85 MCQs across Numerical, Verbal, Reasoning & Advanced sections.",
    durationMin: 120,
    accent: "from-sky-500 to-emerald-400",
    icon: "🧮",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: aptitudeQuestions,
    sections: aptitudeSections,
    schedule: { round: 1, date: "18 Jun 2026", time: "09:00 AM – 11:00 AM", durationLabel: "2 Hours", startAt: "2026-06-18T09:00:00+05:30", endAt: "2026-06-18T11:00:00+05:30" },
  },
  {
    id: "dsa",
    title: "DSA Test",
    description: "10 DSA MCQs + 2 coding problems + 2 advanced coding problems — single exam.",
    durationMin: 180,
    accent: "from-indigo-500 to-cyan-400",
    icon: "🧩",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: dsaQuestions,
    schedule: { round: 2, date: "18 Jun 2026", time: "02:00 PM – 05:00 PM", durationLabel: "3 Hours", startAt: "2026-06-18T14:00:00+05:30", endAt: "2026-06-18T17:00:00+05:30" },
  },
  {
    id: "coding",
    title: "Coding Round",
    description: "Code reasoning, dry-run & output prediction.",
    durationMin: 150,
    accent: "from-blue-600 to-teal-400",
    icon: "💻",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: placeholder("Coding"),
    schedule: { round: 3, date: "18 Jun 2026", time: "06:00 PM – 08:30 PM", durationLabel: "2 Hours 30 Minutes", startAt: "2026-06-18T18:00:00+05:30", endAt: "2026-06-18T20:30:00+05:30" },
  },
  {
    id: "technical",
    title: "Technical Assessment",
    description: "50 scenario-based debugging & integration MCQs.",
    durationMin: 90,
    accent: "from-emerald-500 to-lime-400",
    icon: "⚙️",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: technicalQuestions,
    schedule: { round: 4, date: "19 Jun 2026", time: "02:00 PM – 03:30 PM", durationLabel: "1 Hour 30 Minutes", startAt: "2026-06-19T14:00:00+05:30", endAt: "2026-06-19T15:30:00+05:30" },
  },
  {
    id: "system",
    title: "Basic Understanding Assessment",
    description: "40 MCQs on databases, ACID, normalization, client-server & architecture fundamentals.",
    durationMin: 90,
    accent: "from-violet-500 to-sky-400",
    icon: "🖥️",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: systemQuestions,
    schedule: { round: 5, date: "19 Jun 2026", time: "08:00 PM – 09:30 PM", durationLabel: "1 Hour 30 Minutes", startAt: "2026-06-19T20:00:00+05:30", endAt: "2026-06-19T21:30:00+05:30" },
  },
];

export function getExam(id: string): ExamCategory | undefined {
  return EXAMS.find((e) => e.id === id);
}

function shuffle<T>(arr: T[]): T[] {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function prepareExam(exam: ExamCategory): Question[] {
  // For sectioned exams, keep the question order stable (Q1, Q2, …).
  // For unsectioned exams, shuffle questions as before. Options are always
  // shuffled so candidates can't memorise option positions.
  const ordered = exam.sections ? exam.questions.slice() : shuffle(exam.questions);
  return ordered.map((q) => {
    const idxs = q.options.map((_, i) => i);
    const shuffled = shuffle(idxs);
    const options = shuffled.map((i) => q.options[i]);
    const answer = shuffled.indexOf(q.answer);
    return { ...q, options, answer };
  });
}
