export interface Question {
  id: number;
  q: string;
  options: string[];
  answer: number;
}

export interface ExamCategory {
  id: string;
  title: string;
  description: string;
  durationMin: number;
  accent: string;
  icon: string;
  marksPerQuestion: number;
  negativeMarkFraction: number;
  questions: Question[];
}

const placeholder = (topic: string): Question[] =>
  Array.from({ length: 5 }).map((_, i) => ({
    id: i + 1,
    q: `[${topic}] Sample question ${i + 1} - replace with real question.`,
    options: ["Option A", "Option B", "Option C", "Option D", "None of the above"],
    answer: 0,
  }));

const NOTA = "None of the above.";
const Q = (id: number, q: string, options: string[], answer: number): Question => ({ id, q, options, answer });

const aptitudeQuestions: Question[] = [
  Q(1, "In an exhaustive macroeconomic analysis of post-industrial agrarian supply chains, researchers observed a profound operational paradox: while the systemic implementation of high-frequency automated harvesting sub-routines universally escalated the absolute raw material yield across all tested demographics, the aggregate profitability metrics of the adopting cooperatives paradoxically demonstrated a statistically significant negative correlation over a fiscal quadriennium. Further forensic market auditing revealed that the artificially accelerated yield vectors induced a hyper-localized market saturation, thereby completely destabilizing the equilibrium of the localized price-elasticity curve. Based strictly on the empirical data and causal relationships explicitly articulated in this synopsis, which of the following extrapolations represents the most logically rigorous deduction?",
    ["The deployment of automated harvesting sub-routines is inherently detrimental to the long-term ecological sustainability of agrarian sectors.", "The aggregate financial deficit incurred by the cooperatives is directly and exclusively attributable to the exorbitant mechanical maintenance costs of the automated systems.", "A quantifiable escalation in raw material output does not unconditionally guarantee a corresponding proportional increase in the aggregate profitability of the producing entity.", "Hyper-localized market saturation is an inevitable, unavoidable consequence of all technological modernization efforts within the agricultural industry.", NOTA], 2),
  Q(2, "Algorithm Alpha, operating in isolation, requires 24 continuous hours to process one petabyte of data. Algorithm Beta requires 36 hours for the same volume. If both algorithms are executed concurrently for exactly 8 hours, what fraction of the one-petabyte dataset will remain unprocessed?",
    ["5/9", "4/9", "7/18", "11/18", NOTA], 1),
  Q(3, "A regulatory compliance officer is auditing a designated consumption zone governed by a strict statutory mandate: 'Any biological entity engaging in the ingestion of ethanol-based beverages must possess a verified chronological age strictly exceeding 18 solar years.' The officer observes four entities: Entity Alpha is actively consuming an ethanol-based beverage; Entity Beta is consuming a non-alcoholic botanical extract; Entity Gamma's official identification verifies a chronological age of precisely 16 solar years; and Entity Delta possesses documentation proving an age of 22 solar years. To rigorously prove that no statutory violations are occurring, the officer must execute a state-verification procedure on which precise combination of entities?",
    ["Only Entity Alpha and Entity Gamma", "Only Entity Alpha", "Entity Alpha, Beta, Gamma, and Delta", "Only Entity Alpha, Gamma, and Delta", NOTA], 0),
  Q(4, "Consider a continuous scalar variable x in the reals satisfying x^2 + x - 1 = 0. Deduce the exact numerical evaluation of the higher-order expression x^4 + 1/x^4.",
    ["1", "5", "7", "9", NOTA], 2),
  Q(5, "During a high-altitude expedition, five researchers P, Q, R, S, T must arrange their sleeping bags in a strictly linear adjacent sequence. P, Q, and T strictly mandate non-adjacent placement relative to R. Furthermore, P and S expressly prohibit any proximity to Q's immediate left or right coordinates. Identify the exact left-to-right positional sequence.",
    ["R, S, P, T, Q", "Q, S, P, T, R", "R, P, S, T, Q", "P, S, R, T, Q", NOTA], 0),
  Q(6, "A primary containment vessel holds exactly 40 cubic meters of brine at a 15% volumetric salinity concentration. Due to a prolonged thermal exposure cycle, exactly 16 cubic meters of the H2O solvent is evaporated, leaving the entire precipitate mass suspended. Determine the updated percentage salinity of the concentrated solution.",
    ["20%", "22.5%", "25%", "31.5%", NOTA], 2),
  Q(7, "An algorithmic quantitative trading protocol liquidated a digital asset, realizing an 18% financial deficit relative to its initial fiat acquisition cost. Had the asset been liquidated at a price point exactly 680 INR higher, the transaction would have yielded a 16% fiscal surplus instead of a deficit. Determine the absolute initial fiat acquisition cost.",
    ["1,800 INR", "2,000 INR", "2,500 INR", "3,400 INR", NOTA], 1),
  Q(8, "u + v = 7 and u*v = 10. Determine u^3 + v^3.", ["125", "133", "217", "343", NOTA], 1),
  Q(9, "A cube painted on the exterior is partitioned into 27 isometric sub-cubes. How many have paint on exactly two faces?", ["4", "8", "12", "24", NOTA], 2),
  Q(10, "Despite the investigator's assertion that the new framework would establish a transparent, universally applicable, and ________ paradigm for predicting anomalous particle trajectories, the publication was so densely layered with contradictory axioms and recursive logic loops that it only served to ________ the very phenomena it was engineered to clarify.",
    ["unambiguous ... obfuscate", "convoluted ... elucidate", "irrefutable ... synthesize", "esoteric ... propagate", NOTA], 0),
  Q(11, "5 modules (M1..M5, must stay consecutive in order) + 7 distinguishable chassis placed linearly. Total unique configurations?", ["5,040", "40,320", "3,628,800", "39,916,800", NOTA], 1),
  Q(12, "x + y = 32, |x - y| = 18. Compute xy.", ["175", "225", "400", "576", NOTA], 0),
  Q(13, "5^(2y - 1) = 3125. Evaluate 4^(y + 2).", ["256", "1024", "4096", "16384", NOTA], 1),
  Q(14, "Current population is 1,102,500 after 2 years of compounding at 5%/yr. Baseline 24 months prior?", ["1,000,000", "1,025,000", "1,050,000", "995,000", NOTA], 0),
  Q(15, "Two locomotives leave the same origin at 07:00; one North at 80 km/h, one South at 100 km/h. When is the separation exactly 540 km?", ["09:00", "10:00", "11:00", "11:30", NOTA], 1),
  Q(16, "Cohort of 250: 130 react to X, 110 react to Y, 40 react to both. How many are asymptomatic?", ["30", "50", "70", "90", NOTA], 1),
  Q(17, "Alpha has active:solvent = 1:3; Beta 1:4. Blended 2:3 by volume. Alpha alone gives 20% profit at its per-liter price. Mixture is priced equal to Alpha (solvent free). Profit/loss % on mixture?",
    ["25.55% profit", "36.36% profit", "18.18% deficit", "42.00% profit", NOTA], 1),
  Q(18, "A UAV goes 24 km North, yaws 90° starboard (East) and goes 7 km. Displacement magnitude and heading?",
    ["25 km, NE", "31 km, NE", "25 km, NW", "31 km, NW", NOTA], 0),
  Q(19, "12,000 INR invested at 5% p.a. compounded annually for 3 years. Total accumulated interest?",
    ["1,800.00", "1,891.50", "1,925.25", "2,050.00", NOTA], 1),
  Q(20, "20 microprocessors (8 defective, 12 functional). Draw 3 without replacement. P(all 3 functional)?",
    ["11/57", "33/95", "27/125", "12/57", NOTA], 0),
  Q(21, "A 200 m maglev at 144 km/h traverses a 600 m tunnel. Seconds from nose entering to tail exiting?",
    ["15", "20", "22.5", "25", NOTA], 1),
  Q(22, "A circular wafer's radius increases by 15%. % increase in area?",
    ["15.00%", "30.00%", "32.25%", "35.50%", NOTA], 2),
  Q(23, "Data fluctuations defy all known frameworks — impossible to rationalize, interpret, or articulate. Best single word?",
    ["Incomprehensible", "Indelible", "Inextricable", "Infallible", NOTA], 0),
  Q(24, "Despite a media campaign of baseless allegations, the magistrate's reputation proved completely ________.",
    ["undiminished", "resolved", "illegal", "uncertain", NOTA], 0),
  Q(25, "Acute angle between hour and minute hands at 08:30?", ["60°", "75°", "85°", "90°", NOTA], 1),
  Q(26, "x + y = 5 and x*y = 6. Find x^3 + y^3.", ["35", "91", "125", "215", NOTA], 0),
  Q(27, "Statement: 'Ban diesel vehicles older than 10 years to improve air quality.' I: Older diesel vehicles pollute significantly. II: Banning is the only way to improve air quality. Implicit?",
    ["Only I", "Only II", "Both I and II", "Neither", NOTA], 0),
  Q(28, "Bag with 5 red, 7 blue balls. Draw 2 without replacement. P(both red)?", ["5/33", "5/12", "25/144", "10/33", NOTA], 0),
  Q(29, "Paper folded in half horizontally then vertically. One circular hole punched through all layers. How many holes when fully unfolded?",
    ["1", "2", "4", "8", NOTA], 2),
  Q(30, "Radius of a circle increased by 20%. % increase in area?", ["20%", "40%", "44%", "400%", NOTA], 2),
];

// 20 Pro-Level System Design & Architecture MCQs.
const systemQuestions: Question[] = [
  Q(1, "In an HTTP/2 architecture, multiple client requests are multiplexed over a single TCP connection to an Express API Gateway. If a single packet containing a partial payload for Request A is lost in transit, what happens to Request B, which is fully received and queued behind it?",
    ["Request B is processed immediately because HTTP/2 streams are independent at the application layer.",
     "Request B is blocked until the missing packet for Request A is retransmitted and acknowledged, due to TCP's strict ordered delivery (TCP head-of-line blocking).",
     "The TCP connection automatically falls back to HTTP/1.1 to process Request B.",
     "The API Gateway drops both requests and forces a new TLS handshake.", NOTA], 1),
  Q(2, "You are designing a high-throughput time-series DB and choose an LSM-Tree over a B-Tree. What is a primary trade-off of LSM-Trees?",
    ["LSM-Trees suffer from extreme Write Amplification, burning out SSDs faster than B-Trees.",
     "LSM-Trees provide faster reads but slower writes than B-Trees.",
     "LSM-Trees require continuous background compaction that can cause periodic latency spikes during reads.",
     "LSM-Trees cannot support range queries or sequential scans.", NOTA], 2),
  Q(3, "A high-frequency trading platform needs minimum latency. The load balancer only needs to distribute traffic based on IP and Port — no HTTP inspection. Which strategy fits?",
    ["Layer 7 HTTP Reverse Proxy", "Layer 4 Transport Level Load Balancing", "Application-Level Anycast", "DNS Round Robin with low TTL", NOTA], 1),
  Q(4, "According to PACELC, what trade-off must a distributed DB (Cassandra/DynamoDB) make during normal operation when there is Else (E) no partition?",
    ["Latency (L) versus Consistency (C)", "Availability (A) versus Durability (D)", "Partition Tolerance (P) versus Latency (L)", "Consistency (C) versus Partition Tolerance (P)", NOTA], 0),
  Q(5, "CQRS with normalized PostgreSQL Command DB and denormalized ElasticSearch Query DB. Most significant architectural challenge?",
    ["The system can no longer handle concurrent writes.",
     "You must handle Eventual Consistency between Command and Query DBs — users may read stale data right after a write.",
     "ElasticSearch cannot be horizontally scaled if used only for queries.",
     "The API Gateway must execute 2PC across both DBs for every read.", NOTA], 1),
  Q(6, "A Kafka topic has 10 partitions. You scale a Node.js consumer microservice to 12 instances in the same Consumer Group. What happens?",
    ["All 12 instances process messages concurrently, +20% throughput.",
     "10 instances process messages (one partition each); 2 instances sit idle.",
     "The broker dynamically splits two partitions so all 12 receive data.",
     "A Split-Brain occurs causing duplicate processing on all instances.", NOTA], 1),
  Q(7, "What fundamental difference gives gRPC its massive performance boost over JSON/REST?",
    ["gRPC uses UDP instead of TCP, eliminating handshake latency.",
     "gRPC uses Protocol Buffers — compressed, strongly-typed binary instead of human-readable text.",
     "gRPC auto-implements the Circuit Breaker at the network layer.",
     "gRPC maintains stateful connections, eliminating the need for a database.", NOTA], 1),
  Q(8, "In 2PC, after all Participants reply 'Yes' the Coordinator crashes before sending Commit. What state are the Participants in?",
    ["They auto-abort after a 5-second timeout.",
     "They are blocked and must hold locks indefinitely until the Coordinator recovers or an admin intervenes.",
     "They elect a new Coordinator and immediately commit.",
     "They silently drop the transaction and accept new writes.", NOTA], 1),
  Q(9, "10,000 concurrent requests miss the cache simultaneously and stampede the DB. Which strategy actively prevents this without serving stale data forever?",
    ["Increase TTL to 30 days.",
     "Probabilistic Early Expiration or Mutex Locks (Request Coalescing).",
     "Implement an LRU eviction policy.",
     "Switch from Memcached to Redis.", NOTA], 1),
  Q(10, "Live scoreboard pushes updates every 500ms; client never sends data back. Why is SSE often architecturally superior to WebSockets here?",
    ["SSE is bidirectional; WebSockets are strictly unidirectional.",
     "SSE runs over standard HTTP/1.1 or HTTP/2 — native firewall support, multiplexing, and built-in automatic reconnection without a custom transport.",
     "WebSockets cannot transmit binary data.",
     "SSE uses UDP and is immune to head-of-line blocking.", NOTA], 1),
  Q(11, "How does the Strangler Fig migration pattern operate at the system level?",
    ["A proxy / API Gateway sits in front of the monolith. As new microservices are built, the proxy gradually routes specific URL paths to them until the monolith is decommissioned.",
     "The legacy DB is replicated to the cloud and the monolith reads from the replica.",
     "The monolith's code is auto-transpiled from Java to Node.js with an LLM.",
     "Traffic to the monolith is throttled to force users onto the new system.", NOTA], 0),
  Q(12, "Repeatable Read isolation. TxA sees 5 PENDING orders. TxB inserts a new PENDING order and commits. TxA re-runs the same query. Without next-key locking, what anomaly occurs?",
    ["Dirty Read", "Non-Repeatable Read", "Phantom Read — TxA now sees 6 results as a new row matches the range.", "Write Skew", NOTA], 2),
  Q(13, "Two-node MongoDB cluster split across two DCs. Network link drops; both promote themselves to Primary → Split-Brain. How is this prevented in modern systems?",
    ["Strict Last-Write-Wins conflict resolution.",
     "An odd number of voting nodes (e.g. 3) with strict majority Quorum required to elect a Primary or accept writes.",
     "Auto shutdown if ping > 500ms.",
     "Manually pause the DB during outages.", NOTA], 1),
  Q(14, "Petabytes of immutable video files served directly to Edge CDNs. Best storage architecture?",
    ["Block Storage (EBS) for byte-level modification.",
     "Object Storage (S3) — scales infinitely, immutable objects, rich metadata, native HTTP access.",
     "Relational DB BLOBs for strict ACID on video playback.",
     "File Storage (EFS) so thousands of servers can mount the same directory natively.", NOTA], 1),
  Q(15, "RabbitMQ worker keeps crashing on the same poison-pill message which is requeued infinitely. How is this resolved at the system level?",
    ["Silently ACK and delete all failed messages.",
     "Configure broker retry policy to route the message to a Dead Letter Queue (DLQ) after N failed attempts.",
     "Increase the worker's RAM allocation.",
     "Switch to synchronous HTTP REST.", NOTA], 1),
  Q(16, "Stateless JWTs — need to instantly revoke one user's 60-min token without a per-request DB bottleneck. Best approach?",
    ["Rotate the master signing secret (invalidates everyone globally).",
     "Maintain a fast centralized Deny List of revoked jti IDs in Redis, checked by the Gateway on every request.",
     "Send an HTTP DELETE to wipe the client's local storage.",
     "You cannot revoke a stateless JWT; wait for expiry.", NOTA], 1),
  Q(17, "hash(key) % N breaks badly when a node dies. Which concept maps nodes/keys on a virtual ring so only a small fraction of keys are remapped on node loss?",
    ["Linear Probing", "Round-Robin Hashing", "Consistent Hashing", "SHA-256 Cryptographic Hashing", NOTA], 2),
  Q(18, "Circuit Breaker is Open after failures. The downstream service recovers. The breaker enters a state that allows a limited number of test requests to verify recovery. What is this state called?",
    ["Closed", "Half-Open", "Throttled", "Dead-Letter", NOTA], 1),
  Q(19, "Token bucket: max 10 tokens, refill 1/sec. User idle 5 minutes, then sends 15 concurrent requests. What happens?",
    ["10 requests processed immediately (burst); 5 rejected with 429.",
     "All 15 processed — 300s of unused capacity is built up.",
     "All 15 processed strictly at 1 req/sec for 15 seconds.",
     "All 15 rejected — exceed the 1/sec refill rate.", NOTA], 0),
  Q(20, "High-contention ticketing system using Optimistic Concurrency Control with version numbers. Primary drawback vs. Pessimistic Locking?",
    ["OCC places exclusive locks freezing the DB for readers.",
     "OCC requires active WebSocket connections.",
     "Under heavy contention, OCC produces many aborted txns (HTTP 409 Conflicts), forcing heavy app-layer retry logic.",
     "OCC violates ACID isolation.", NOTA], 2),
];

// 15 Pro-Level Fundamental Coding & Integration MCQs.
const technicalQuestions: Question[] = [
  Q(1, "Legacy Express v4 route: app.get('/data', async (req,res,next) => { const d = await fetchFromDB(); res.json(d); }). If fetchFromDB rejects, what happens?",
    ["Express auto-catches and forwards to the (err,req,res,next) error middleware.",
     "Client gets a generic 500 automatically.",
     "The request hangs until timeout; an UnhandledPromiseRejection warning is logged and may crash the Node process.",
     "Express returns a 404.", NOTA], 2),
  Q(2, "GET /transactions over 50M rows with ?limit=100&offset=4999900 takes 8s. Standard API design fix?",
    ["Cursor-based pagination (?limit=100&after=cursor_id) — DB uses an index to jump to the start instead of scanning + skipping millions.",
     "Cache all 50M rows in Redis.",
     "Raise limit to 10,000 so fewer requests are needed.",
     "Use SELECT COUNT(*) to pre-calculate all pages.", NOTA], 0),
  Q(3, "Stripe webhooks: attacker replays a valid payload 500x to double-credit. Fundamental fix?",
    ["Validate JSON payload shape against a TS interface.",
     "Verify the cryptographic Stripe-Signature (which contains a timestamp) and reject payloads older than a few minutes.",
     "Firewall to only accept webhooks from US IPs.",
     "Only allow POST, reject PUT.", NOTA], 1),
  Q(4, "Node.js OOM crash; heap shows millions of trapped large arrays. Most likely culprit?",
    ["JSON.parse on a very large response.",
     "An event listener on a long-lived object (e.g. process, server) closes over outer-scope vars, preventing GC.",
     "Recursive function without a base case (Call Stack Exceeded).",
     "Forgetting new when instantiating an ES6 class.", NOTA], 1),
  Q(5, "Prevent Lost Updates on PUT /articles/123 via Optimistic Concurrency. Which HTTP headers?",
    ["Server sends ETag; client sends Cache-Control: no-cache next time.",
     "Server sends ETag (hash). Client sends If-Match with that hash on PUT. Server returns 412 Precondition Failed on mismatch.",
     "Server sends Authorization; client responds with X-Forwarded-For.",
     "Strict-Transport-Security to encrypt the payload.", NOTA], 1),
  Q(6, "Third-party API frequently returns 429 / 503. Industry-standard resilient integration pattern?",
    ["while(true) retry every 10ms.",
     "setTimeout 60s then retry once.",
     "Exponential Backoff with Jitter — progressively increase wait + add randomness to avoid synchronized Thundering Herd.",
     "Immediately return 200 to your client and drop the call.", NOTA], 2),
  Q(7, "React app at http://localhost:3000 POSTs with a custom X-Tenant-ID header to http://api.example.com. Browser blocks: CORS preflight failed. What is actually failing?",
    ["The OPTIONS preflight response is missing Access-Control-Allow-Headers: X-Tenant-ID, so the browser blocks the actual POST.",
     "Express is missing body-parser so the preflight JSON can't be read.",
     "Axios is missing credentials: 'include'.",
     "Server rejected because the frontend is not on HTTPS.", NOTA], 0),
  Q(8, "Express proxies a 5GB S3 video via const file = await s3.getObject(); res.send(file.body); — Node crashes. Correct rewrite?",
    ["Bump heap to 8GB with --max-old-space-size=8192.",
     "Download the file to local disk first then fs.readFileSync.",
     "zlib-compress to ZIP before sending.",
     "Pipe the S3 readable stream directly into the Express response (s3Stream.pipe(res)) so chunks forward without buffering the whole file in RAM.", NOTA], 3),
  Q(9, "An endpoint does heavy synchronous math. All other clients experience massive latency and health-checks fail. Why?",
    ["Synchronous JS blocks the single-threaded Node Event Loop, preventing acceptance/processing of any other HTTP requests or async callbacks.",
     "GC pauses to clean math variables.",
     "Router uses HTTP/1.1 instead of HTTP/2.",
     "DB connection pool is exhausted.", NOTA], 0),
  Q(10, "PATCH /users/:id does User.findByIdAndUpdate(req.params.id, req.body). Attacker sends {isAdmin:true} and becomes admin. Vulnerability + fix?",
    ["SQL Injection — escape input.",
     "Mass Assignment / Over-posting — explicitly destructure permitted fields (e.g. const {name,email}=req.body) before update.",
     "XSS — sanitize HTML in payload.",
     "Broken Authentication — rotate JWT secret.", NOTA], 1),
  Q(11, "GraphQL fetches 50 users, then 50 separate Company queries — the N+1 problem. Standard fix?",
    ["Use Facebook's DataLoader to batch + cache the 50 calls into a single SELECT ... WHERE id IN (...).",
     "Switch PostgreSQL to MongoDB.",
     "Force the client to make separate REST calls.",
     "Add a composite index on the Company table.", NOTA], 0),
  Q(12, "WebSocket chat drops after exactly 60s idle with no errors. Most likely cause?",
    ["ws library has a hardcoded 60s cap.",
     "Browser GC deleted the WebSocket variable.",
     "An intermediate reverse proxy (Nginx / AWS LB) closed the idle TCP connection because no Ping/Pong heartbeats were sent.",
     "React component unmounted in the background.", NOTA], 2),
  Q(13, "POST /refunds — client may retry on timeout, risking double refund. Safe API design?",
    ["Change to GET (naturally idempotent).",
     "Require a unique Idempotency-Key header; if a successful txn with that key exists, return the cached response without re-processing.",
     "Disable the user's account on duplicate payload.",
     "Rely on the DB primary key auto-increment.", NOTA], 1),
  Q(14, "Node worker uses a PG pool. After exactly 10 jobs it freezes (no CPU). What coding error?",
  Q(14, "Node worker uses a PG pool. After exactly 10 jobs it freezes (no CPU). What coding error?",
    ["Forgot pool.release() / client.end() inside a finally block — connection pool exhausted.",
     "PostgreSQL ran out of disk space.",
     "Worker built with an older V8.",
     "Queue payloads exceed 16MB.", NOTA], 0),
  Q(15, "POST /users/batch with 1000 users; 999 valid, 1 invalid email. Most appropriate RESTful behavior?",
    ["Rollback all and return 400 so the client knows what failed.",
     "Insert the 999, silently ignore the bad one, return 200.",
     "Insert the 999 and return 207 Multi-Status with per-item 201 Created / 400 Bad Request details.",
     "Halt, return 500, trigger PagerDuty.", NOTA], 2),
];

export const EXAMS: ExamCategory[] = [
  {
    id: "aptitude",
    title: "Aptitude Test",
    description: "Quantitative, logical reasoning & verbal ability.",
    durationMin: 40,
    accent: "from-sky-500 to-emerald-400",
    icon: "🧮",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: aptitudeQuestions,
  },
  {
    id: "dsa",
    title: "DSA Test",
    description: "Data Structures & Algorithms MCQs.",
    durationMin: 20,
    accent: "from-indigo-500 to-cyan-400",
    icon: "🧩",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: placeholder("DSA"),
  },
  {
    id: "coding",
    title: "Coding Round",
    description: "Code reasoning, dry-run & output prediction.",
    durationMin: 30,
    accent: "from-blue-600 to-teal-400",
    icon: "💻",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: placeholder("Coding"),
  },
  {
    id: "system",
    title: "System Understanding",
    description: "Pro-level system design, architecture, networking & DB internals.",
    durationMin: 25,
    accent: "from-violet-500 to-sky-400",
    icon: "🖥️",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: systemQuestions,
  },
  {
    id: "technical",
    title: "Technical Assessment",
    description: "Fundamental coding, debugging & integration tasks (API, Node.js, REST).",
    durationMin: 25,
    accent: "from-emerald-500 to-lime-400",
    icon: "⚙️",
    marksPerQuestion: 2,
    negativeMarkFraction: 0.25,
    questions: technicalQuestions,
  },
];

export const getExam = (id: string) => EXAMS.find((e) => e.id === id);

export function shuffle<T>(arr: T[]): T[] {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function prepareExam(exam: ExamCategory): Question[] {
  return shuffle(exam.questions).map((q) => {
    const idxs = shuffle(q.options.map((_, i) => i));
    const remap = idxs.map((i) => q.options[i]);
    return { ...q, options: remap, answer: idxs.indexOf(q.answer) };
  });
}
